WebbuyMe/Areas/Admin/Controllers/ProductTypesController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebbuyMe.Data;
using WebbuyMe.Models;

namespace WebbuyMe.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductTypesController : Controller
    {

        private readonly ApplicationDbContext _db;

        public ProductTypesController(ApplicationDbContext db)
        {
            _db = db;
        }
        public IActionResult Index()
        {
            var dataList = _db.productTypes.ToList();

            if (TempData["test"] != null)
            {
             
                ViewBag.employee = TempData["test"].ToString();

            }


            return View(dataList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ProductTypes product)
        {
            if (ModelState.IsValid)
            {
                _db.productTypes.Add(product);
                await _db.SaveChangesAsync();
                TempData["test"] = "Data has been added";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(_db.productTypes.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(ProductTypes product)
        {
            if (ModelState.IsValid)
            {
                _db.productTypes.Update(product);
                await _db.SaveChangesAsync();
                TempData["test"] = "Data has been Edit";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }



        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(_db.productTypes.Find(id));
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var del = await _db.productTypes.FindAsync(id);
            _db.Remove(del);
            await _db.SaveChangesAsync();
            TempData["test"] = "Data has been Deleted";
            return RedirectToAction(nameof(Index));
        }

    }
}

WebbuyMe/Areas/Admin/Controllers/ProductsController.cs
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Hosting.Internal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using WebbuyMe.Data;
using WebbuyMe.Models;
using WebbuyMe.Models.ViewModel;
using WebbuyMe.Utility;

namespace WebbuyMe.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class ProductsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly HostingEnvironment _hostingEnvironment;

        [BindProperty]
        public ProductsViewModel ProductsVM { get; set; }

        public ProductsController(ApplicationDbContext context, HostingEnvironment hostingEnvironment)
        {
            _hostingEnvironment = hostingEnvironment;
            _context = context;

            ProductsVM = new ProductsViewModel()
            {
                ProductTypes = _context.productTypes.ToList(),
                SpecialTags = _context.specialTags.ToList(),
                Products = new Models.Products()
            };

        }
        public async Task<IActionResult> Index()
        {
            var products = _context.products.Include(m => m.ProductTypes).Include(m => m.SpecialTags);
            return View(await products.ToListAsync());
        }

        public IActionResult Create()
        {
            return View(ProductsVM);
        }

        [HttpPost, ActionName("Create")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> CreatePost()
        {
            if (!ModelState.IsValid)
            {
                return View(ProductsVM);
            }


            _context.products.Add(ProductsVM.Products);
            await _context.SaveChangesAsync();

            //Image being saved
            string webRoothPath = _hostingEnvironment.WebRootPath;
            var files = HttpContext.Request.Form.Files;

            var productsFromDb = _context.products.Find(ProductsVM.Products.Id);

            if (files.Count != 0)
            {
                var uploads = Path.Combine(webRoothPath, SD.ImageFolder);
                var extension = Path.GetExtension(files[0].FileName);

                using (var filestream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension), FileMode.Create))
                {
                    files[0].CopyTo(filestream);
                }
                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extension;
            }
            else
            {
                //when user doesnot upload image
                var uploads = Path.Combine(webRoothPath, SD.ImageFolder + @"\" + SD.DefaultProductImage);
                System.IO.File.Copy(uploads, webRoothPath + @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png");
                productsFromDb.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + ".png";
            }
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));

        }



        [HttpGet]
        public async Task<IActionResult> Edit(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _context.products.Include(m => m.ProductTypes)
                                                         .Include(m => m.SpecialTags)
                                                         .SingleOrDefaultAsync(m => m.Id == Id);
            if (ProductsVM.Products == null)
            {
                return NotFound();
            }
            return View(ProductsVM);
        }

        [HttpPost, ActionName("Edit")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> EditPost(int id)
        {
            if (ModelState.IsValid)
            {
                string webRootPath = _hostingEnvironment.WebRootPath;
                var files = HttpContext.Request.Form.Files;

                var productFromDb = _context.products.Where(x => x.Id == ProductsVM.Products.Id).FirstOrDefault();

                if (files.Count() > 0 && files[0] != null)
                {
                    //if user upload new Image
                    var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                    var extension_new = Path.GetExtension(files[0].FileName);
                    var extension_old = Path.GetExtension(productFromDb.Image);

                    if (System.IO.File.Exists(Path.Combine(uploads, ProductsVM.Products.Id + extension_old)))
                    {
                        System.IO.File.Delete(Path.Combine(uploads, ProductsVM.Products.Id + extension_old));
                    }

                    using (var filestream = new FileStream(Path.Combine(uploads, ProductsVM.Products.Id + extension_new), FileMode.Create))
                    {
                        files[0].CopyTo(filestream);
                    }
                    ProductsVM.Products.Image = @"\" + SD.ImageFolder + @"\" + ProductsVM.Products.Id + extension_new;
                }

                if (ProductsVM.Products.Image != null)
                {
                    productFromDb.Image = ProductsVM.Products.Image;
                }
                productFromDb.Name = ProductsVM.Products.Name;
                productFromDb.Price = ProductsVM.Products.Price;
                productFromDb.Available = ProductsVM.Products.Available;
                productFromDb.ProductTypeId = ProductsVM.Products.ProductTypeId;
                productFromDb.SpecialTagsId = ProductsVM.Products.SpecialTagsId;
                productFromDb.ShadeColor = ProductsVM.Products.ShadeColor;
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));


            }

            return View(ProductsVM);

        }


        [HttpGet]
        public async Task<IActionResult> Details(int? Id)
        {
            if (Id == null)
            {
                return NotFound();
            }

            ProductsVM.Products = await _context.products.Include(m => m.ProductTypes)
                                                         .Include(m => m.SpecialTags)
                                                         .SingleOrDefaultAsync(m => m.Id == Id);
            if (ProductsVM.Products == null)
            {
                return NotFound();
            }
            return View(ProductsVM);
        }

        [HttpGet]
        public async Task<IActionResult> Delete(int Id)
        {
            string webRootPath = _hostingEnvironment.WebRootPath;
            Products products = await _context.products.FindAsync(Id);

            if (products == null)
            {
                return NotFound();
            }
            else
            {
                var uploads = Path.Combine(webRootPath, SD.ImageFolder);
                var extension = Path.GetExtension(products.Image);

                if (System.IO.File.Exists(Path.Combine(uploads, products.Id + extension)))
                {
                    System.IO.File.Delete(Path.Combine(uploads, products.Id + extension));
                }
                _context.products.Remove(products);
                await _context.SaveChangesAsync();

                return RedirectToAction(nameof(Index));
            }
        }

    }
}

WebbuyMe/Areas/Admin/Controllers/SpecialTagsController.cs
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System.Threading.Tasks;
using WebbuyMe.Data;
using WebbuyMe.Models;

namespace WebbuyMe.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SpecialTagsController : Controller
    {
        private readonly ApplicationDbContext _db;

        public SpecialTagsController(ApplicationDbContext db)
        {
            _db = db;
        }

        public IActionResult Index()
        {
            var dataList = _db.specialTags.ToList();

            if (TempData["test"] != null)
            {

                ViewBag.employee = TempData["test"].ToString();

            }


            return View(dataList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(SpecialTags tags)
        {
            if (ModelState.IsValid)
            {
                _db.specialTags.Add(tags);
                await _db.SaveChangesAsync();
                TempData["test"] = "Data has been added";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }


        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(_db.specialTags.Find(id));
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(SpecialTags tags)
        {
            if (ModelState.IsValid)
            {
                _db.specialTags.Update(tags);
                await _db.SaveChangesAsync();
                TempData["test"] = "Data has been Edit";
                return RedirectToAction(nameof(Index));
            }
            return View();
        }



        [HttpGet]
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            return View(_db.specialTags.Find(id));
        }


        [HttpGet]
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var del = await _db.specialTags.FindAsync(id);
            _db.Remove(del);
            await _db.SaveChangesAsync();
            TempData["test"] = "Data has been Deleted";
            return RedirectToAction(nameof(Index));
        }

    }
}

WebbuyMe/Areas/Customer/Controllers/ShoppingCartController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebbuyMe.Data;
using WebbuyMe.Extensions;
using WebbuyMe.Models;
using WebbuyMe.Models.ViewModel;

namespace WebbuyMe.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShoppingCartController : Controller
    {
        private readonly ApplicationDbContext _db;

        [BindProperty]
        public ShoppingCartViewModel ShoppingCartVM { get; set; }

        public ShoppingCartController(ApplicationDbContext db)
        {
            _db = db;

            ShoppingCartVM = new ShoppingCartViewModel()
            {
                Products = new List<Products>()
            };
        }

        public async Task<IActionResult> Index()
        {
            List<int> lstShoppingCart = HttpContext.Session.Get<List<int>>("ssShoppingCart");
            if (lstShoppingCart != null && lstShoppingCart.Count > 0)
            {
                foreach (var cartItem in lstShoppingCart)
                {
                    Products prod = _db.products.Include(p => p.SpecialTags).Include(p => p.ProductTypes).FirstOrDefault(p => p.Id == cartItem);
                    ShoppingCartVM.Products.Add(prod);
                }
            }
            return View(ShoppingCartVM);
        }

        public IActionResult Remove()
        {
            throw new System.NotImplementedException();
        }
    }
}

WebbuyMe/Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Http;
@using WebbuyMe.Extensions;

@inject IHttpContextAccessor HttpContextAccessor

<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebbuyMe</title>

    <environment include="Development">
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />

        <link rel="stylesheet" href="~/css/bootstrap-datepicker.css" />
        <link rel="stylesheet" href="~/css/bootstrap-datepicker.min.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />


        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="~/css/bootstrap-datepicker.css" />
        <link rel="stylesheet" href="~/css/bootstrap-datepicker.min.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />
        <link rel="stylesheet" href="~/css/jquery.timepicker.min.css" />
        <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.css">
        <link rel="stylesheet" href="~/css/jquery.timepicker.css" />
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
        <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous" />

    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="Admin" asp-controller="Products" asp-action="Index" class="navbar-brand">Webbuy Me</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="Admin" asp-controller="ProductTypes" asp-action="Index">Product Types</a></li>
                    <li><a asp-area="Admin" asp-controller="SpecialTags" asp-action="Index">SpeciaL Tags</a></li>
                    <li><a asp-area="Admin" asp-controller="Products" asp-action="Index">Products</a></li>
                    @if (HttpContextAccessor.HttpContext.Session.Get<List<int>>
                ("ssShoppingCart") != null)
                    {
                        <li style="color:white">
                            <a asp-area="Customer" class="nav-link" asp-controller="ShoppingCart" asp-action="index">
                                <i class="fas fa-shopping-cart"></i> &nbsp;
                                @{
                                    var count = HttpContextAccessor.HttpContext.Session.Get<List<int>>("ssShoppingCart").Count;

                                }
                                (@count)
                            </a>
                        </li>
                    }
                    else
                    {
                        <li style="color:white">
                            <a asp-area="Customer" class="nav-link" asp-controller="ShoppingCart" asp-action="index">
                                <i class="fas fa-shopping-cart"></i> &nbsp;
                                (0)
                            </a>
                        </li>
                    }

                </ul>
                <partial name="_LoginPartial" />
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2020 - WebbuyMe</p>
        </footer>
    </div>

    @*<environment include="Development">
            <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>
            <script src="~/lib/jquery/dist/jquery.js"></script>
            <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
            <script src="~/js/site.js" asp-append-version="true"></script>
            <script src="~/js/jquery.timepicker.min.js"></script>
            <script src="~/js/jquery.timepicker.js"></script>
        </environment>
        <environment exclude="Development">
            <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                    asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                    asp-fallback-test="window.jQuery"
                    crossorigin="anonymous"
                    integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
            </script>
            <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                    asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                    asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                    crossorigin="anonymous"
                    integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
            </script>
            <script src="//cdnjs.cloudflare.com/ajax/libs/timepicker/1.3.5/jquery.timepicker.min.js"></script>

            <script src="~/js/jquery.timepicker.min.js"></script>
            <script src="~/js/jquery.timepicker.js"></script>
            <script src="~/js/site.min.js" asp-append-version="true"></script>
        </environment>*@
    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        <script src="~/js/jquery.timepicker.min.js"></script>
        <script src="~/js/jquery.timepicker.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
        }
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

WebbuyMe/Views/Shared/_TableButtonPartial.cshtml
@model int
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@



<td>
    <a href="@Url.Action("Edit/"+Model)" class="btn btn-primary"><i class="fas fa-edit"></i></a> |
    <a href="@Url.Action("Details/"+Model)" class="btn btn-success"><i class="fas fa-list"></i></a> |
    <a href="@Url.Action("Delete/"+Model)" onclick="return confirm('Are you sure you want to delete?');" class="btn btn-danger"><i class="fas fa-trash"></i></a>
</td>